use crate::{CONTEXT_INDEX_FILENAME, Result, context_index, read_rows};
use std::collections::{BTreeMap, BTreeSet};

/// Every resource derived from the generated dictionary: 32 spelling profiles and the context index.
pub fn spelling(dictionary: &[u8]) -> Result<BTreeMap<String, Vec<u8>>> {
    let mut syllables = BTreeSet::new();
    read_rows(dictionary, "generated-spelling", |key, _| {
        syllables.extend(key.reading.split(' ').map(str::to_owned));
    })?;
    let mut schemas = BTreeMap::new();
    for profile in 0..32 {
        let mut rules = vec![
            "derive/^([nl])ue$/$1ve/".to_owned(),
            "derive/^([jqxy])u/$1v/".to_owned(),
        ];
        for (initial, bit) in [('z', 4), ('c', 8), ('s', 16)] {
            if profile & bit != 0 {
                rules.push(format!("derive/^{initial}h/{initial}/"));
                rules.push(format!("derive/^{initial}([^h])/{initial}h$1/"));
            }
        }
        if profile & 1 != 0 {
            rules.extend([
                "abbrev/^([a-z]).+$/$1/".to_owned(),
                "abbrev/^([zcs]h).+$/$1/".to_owned(),
            ]);
        }
        if profile & 2 != 0 {
            let mut legal = syllables.clone();
            for syllable in &syllables {
                match syllable.as_str() {
                    "nue" => {
                        legal.insert("nve".to_owned());
                    }
                    "lue" => {
                        legal.insert("lve".to_owned());
                    }
                    _ => {}
                }
            }
            for syllable in legal.clone() {
                if syllable.len() >= 2
                    && b"jqxy".contains(&syllable.as_bytes()[0])
                    && syllable.as_bytes()[1] == b'u'
                {
                    legal.insert(format!("{}v{}", &syllable[..1], &syllable[2..]));
                }
            }
            for (initial, bit) in [('z', 4), ('c', 8), ('s', 16)] {
                if profile & bit == 0 {
                    continue;
                }
                for syllable in legal.clone() {
                    if let Some(rest) = syllable.strip_prefix(&format!("{initial}h")) {
                        legal.insert(format!("{initial}{rest}"));
                    }
                }
                for syllable in legal.clone() {
                    if let Some(rest) = syllable.strip_prefix(initial)
                        && !rest.is_empty()
                        && !rest.starts_with('h')
                    {
                        legal.insert(format!("{initial}h{rest}"));
                    }
                }
            }
            rules.extend([
                "derive/^(.*)$/~$1/".to_owned(),
                "fuzz/^~([zcs])h/~h$1/".to_owned(),
                "fuzz/^~([bpmfdtnlgkhjqxrzcsyw])(?=[a-z])/~$1$1/".to_owned(),
                "fuzz/^~(.*)([aeiou])ng$/~$1$2gn/".to_owned(),
                "fuzz/^~(.*)ao$/~$1oa/".to_owned(),
                "fuzz/^~(.*)([iu])a(o|ng?)?$/~$1a$2$3/".to_owned(),
                format!(
                    "erase/^~({})$/",
                    legal.into_iter().collect::<Vec<_>>().join("|")
                ),
                "xform/^~//".to_owned(),
            ]);
        }
        let name = format!("inkflow_spelling_{profile}");
        let rules = rules
            .iter()
            .map(|r| format!("    - {r}"))
            .collect::<Vec<_>>()
            .join("\n");
        let schema = format!(
            "# Generated by IFSpellingGenerator. Compilation dependency only.\nschema:\n  schema_id: {name}\n  name: InkFlow spelling {profile}\n  version: '1.1'\ntranslator:\n  dictionary: pinyin_simp\n  prism: {name}\nspeller:\n  algebra:\n{rules}\n"
        );
        schemas.insert(format!("{name}.schema.yaml"), schema.into_bytes());
    }
    schemas.insert(CONTEXT_INDEX_FILENAME.to_owned(), context_index(dictionary)?);
    Ok(schemas)
}
