#!/bin/bash
set -euo pipefail
destination=${1:?Usage: prepare-spelling.sh DESTINATION}
mkdir -p "$destination"
# Five bits match InputPreferences.spellingProfile. Distinct prism names let idle
# sessions change spelling while another session keeps its current composition.
for ((mask=0; mask<32; mask++)); do
  name="inkflow_spelling_$mask"
  {
    cat <<EOF
# Generated by prepare-spelling.sh. Compilation dependency only.
schema:
  schema_id: $name
  name: InkFlow spelling $mask
  version: '1.0'
translator:
  dictionary: pinyin_simp
  prism: $name
speller:
  algebra:
    - derive/^([nl])ue\$/\$1ve/
    - derive/^([jqxy])u/\$1v/
EOF
    # Fuzzy derivations precede abbreviation; typo aliases follow abbreviation so
    # mistyped initials never become unintended alternative abbreviations.
    for pair in z c s; do
      case "$pair" in z) bit=4 ;; c) bit=8 ;; s) bit=16 ;; esac
      if ((mask & bit)); then
        printf '    - derive/^%sh/%s/\n    - derive/^%s([^h])/%sh$1/\n' "$pair" "$pair" "$pair" "$pair"
      fi
    done
    if ((mask & 1)); then
      cat <<'EOF'
    - abbrev/^([a-z]).+$/$1/
    - abbrev/^([zcs]h).+$/$1/
EOF
    fi
    if ((mask & 2)); then
      cat <<'EOF'
    - fuzz/^([zcs])h/h$1/
    - fuzz/^([bpmfdtnlgkhjqxrzcsyw])(?=[a-z])/$1$1/
    - fuzz/([aeiou])ng$/$1gn/
    - fuzz/ao$/oa/
    - fuzz/([iu])a(o|ng?)?$/a$1$2/
EOF
    fi
  } > "$destination/$name.schema.yaml"
done
